name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev

jobs:
  build_web:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build Web Artifact
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Publish Blazor WebAssembly
        run: dotnet publish src/AgainstTheSpread.Web/AgainstTheSpread.Web.csproj -c Release -o build/web
      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: build/web
          if-no-files-found: error

  build_api:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build API Artifact
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Publish Azure Functions API
        run: dotnet publish src/AgainstTheSpread.Functions/AgainstTheSpread.Functions.csproj -c Release -o build/api
      - name: Upload api artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-dist
          path: build/api
          if-no-files-found: error

  # Don't want smoke environment for now.
  # deploy_smoke:
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   needs: [build_web, build_api]
  #   runs-on: ubuntu-latest
  #   name: Deploy Smoke Environment
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: web-dist
  #         path: web-dist
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: api-dist
  #         path: api-dist
  #     - name: Install OIDC Client from Core Package
  #       run: npm install @actions/core@1.6.0 @actions/http-client
  #     - name: Get Id Token
  #       uses: actions/github-script@v6
  #       id: idtoken
  #       with:
  #         script: |
  #           return await core.getIDToken()
  #         result-encoding: string
  #     - name: Deploy to Smoke
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_0E2F38010 }}
  #         action: "upload"
  #         app_location: "web-dist/wwwroot"
  #         api_location: "api-dist"
  #         skip_app_build: true
  #         skip_api_build: true
  #         github_id_token: ${{ steps.idtoken.outputs.result }}

  deploy_prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build_web, build_api]
    runs-on: ubuntu-latest
    name: Deploy Production Environment
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: web-dist
      - uses: actions/download-artifact@v4
        with:
          name: api-dist
          path: api-dist
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string
      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_0E2F38010 }}
          action: "upload"
          app_location: "web-dist/wwwroot"
          api_location: "api-dist"
          skip_app_build: true
          skip_api_build: true
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_0E2F38010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "."
          action: "close"
